server:
  port: 9002
spring:
  application:
    name: spring-boot-demo
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://172.18.0.10:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
